List<String> listAuthor = [
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Aquele Eita"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Raquel Rodrigues"),
  ("Aquele Eita + Para largar o Rivotril"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Autor Desconhecido"),
  ("Aquele Eita + TCD"),
  ("vana"),
  ("Autor Desconhecido"),
  ("declarais"),
  ("Aquele Eita + Para largar o Rivotril"),
  ("@doses_diarias"),
  ("Aquele Eita + @prazer.poesia"),
  ("Carolina Carmo"),
  ("Felipe Pimentel"),
  ("precisamosfalardeblog.blogspost.com"),
];
