List<String> listPhrase = [
  ("Não deixe transbordar o que já te faz mal. Procure ajuda!"),
  ("Você não está no fundo do poço!"),
  ("Juntos somos mais fortes, não passe por isso sozinho, Fale!"),
  ("Seja lá o que você estiver passando, saiba que nunca foi sua culpa, e nunca será"),
  ("Continue Vivo. Você precisa ouvir sua música favorita mais uma vez, seu bichinho de estimação sentirá falta de você partir, a lua é bonita demais pra nunca mais ser vista, você ainda não viu a próxima temporada daquela série incrível, você tem que ver as luzes de natal esse ano, o barulho da chuva vai te relaxar novamente"),
  ("Você não consegue controlar tudo ao seu redor. E tudo bem"),
  ("Não é egoísmo priorizar a sua saúde mental, mesmo que te digam ao contrario"),
  ("Se a vida é uma história, mesmo que você tropece em uma em uma vírgula, ou caia em algum ponto final, não desista dos próximos capítulos."),
  ("Um capítulo ruim não estraga toda sua história"),
  ("O diálogo cura, tente falar"),
  ("Não tenha vergonha de procurar ajuda profissional"),
  ("NÃO É drama, NÃO É pra chamar atenção, NÃO É a falta de deus, E MUITO MENOS FRESCURA"),
  ("Fale sobre aquilo que lhe dói"),
  ("Eu odeio todas as vezes que amei você antes de mim"),
  ("Ter paciência com o tempo de cada um"),
  ("Você só vence o amanhã se não desistir Hoje!"),
  ("Você exala coisas boas, lembre-se disso sempre que se sentir pouco. Você é muito, é Tudo"),
  ("Você não deve se afetar nem um pouquinho pelo o que os outros pensam de você"),
  ("Você é mais forte do que parece"),
  ("Um dia vai dar tão certo que você nem vai se lembrar que já deu errado"),
  ("A vida é um ciclo constante de términos e inícios"),
  ("Perdoe-se pelas coisas que não dependiam só de você"),
  ("Tá tudo bem em não estar bem"),
];
